// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw2hIw1mz7sOPn9NXltbYDTzdIU-hLVV8',
    appId: '1:439801567699:web:f9bbf4309305801be67726',
    messagingSenderId: '439801567699',
    projectId: 'miniproject1sem1',
    authDomain: 'miniproject1sem1.firebaseapp.com',
    storageBucket: 'miniproject1sem1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWcxmL5dO7XDBgql9w-Ytfd6g14IcHxgo',
    appId: '1:439801567699:android:12ef22150305dca8e67726',
    messagingSenderId: '439801567699',
    projectId: 'miniproject1sem1',
    storageBucket: 'miniproject1sem1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3LapKG7cckJwCQ3HUzFp7sC86DdFB8K4',
    appId: '1:439801567699:ios:144d2cb2be5a31e0e67726',
    messagingSenderId: '439801567699',
    projectId: 'miniproject1sem1',
    storageBucket: 'miniproject1sem1.appspot.com',
    androidClientId: '439801567699-esgej0l1s2jkudf0r5biqar791nl67uu.apps.googleusercontent.com',
    iosClientId: '439801567699-bao6301gvio5aa0080l3i4sisava0lqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcaApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3LapKG7cckJwCQ3HUzFp7sC86DdFB8K4',
    appId: '1:439801567699:ios:144d2cb2be5a31e0e67726',
    messagingSenderId: '439801567699',
    projectId: 'miniproject1sem1',
    storageBucket: 'miniproject1sem1.appspot.com',
    androidClientId: '439801567699-esgej0l1s2jkudf0r5biqar791nl67uu.apps.googleusercontent.com',
    iosClientId: '439801567699-bao6301gvio5aa0080l3i4sisava0lqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcaApp1',
  );
}
